spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  driver-class-name:  org.postgresql.Driver
  hikari:
    schema: self 
 jpa:
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
     format_sql:true
   # show_sql: true
 thymeleaf:
   enabled: true
   cache: false
   check-template-location: true
   prefix: classpath:templates/
   suffix: .html
 mvc:
    static-path-pattern: /static/**   
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
spring.jpa.hibernate.ddl-auto: none

server:
  port: 8080